@echo off
rem THIS SCRIPT IS GENERATED BY CODEX
setlocal
set "ASTRAL_WORKDIR=%~dp0"
set "ASTRAL_PWSH=%ProgramFiles%\PowerShell\7\pwsh.exe"
if exist "%ASTRAL_PWSH%" goto launch
where pwsh.exe >nul 2>&1
if errorlevel 1 goto windows_powershell
set "ASTRAL_PWSH=pwsh.exe"
goto launch
:windows_powershell
set "ASTRAL_PWSH=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"
:launch
"%ASTRAL_PWSH%" -NoLogo -NoProfile -NoExit -Command "Set-Location -LiteralPath $env:ASTRAL_WORKDIR -ErrorAction Stop; $Host.UI.RawUI.WindowTitle = 'Astral Git'; function global:prompt { if ($PWD.ProviderPath.TrimEnd('\') -eq $env:ASTRAL_WORKDIR.TrimEnd('\')) { 'Astral> ' } else { 'PS ' + (Split-Path -Leaf $PWD.Path) + '> ' } }; git status"
if errorlevel 1 pause
endlocal
